name: Upload the test artifacts as Docker image
on:
    push: 
        branches: 
            - 'v*'
        tags: 
            - 'v*'
    workflow_dispatch:


jobs:
    build-a-image-test:
        
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Get version and repo name
              id: version-repo
              run: |
                 export name=$(echo ${{ github.repository }}  | cut -d '/' -f 2) 
                 echo "repo_name=$name" >> "$GITHUB_ENV"
                 echo $name
                 export version=$(echo ${{ github.ref_name }}  | tr -d v)
                 echo "version_no=$version" >> "$GITHUB_ENV"
                 echo $version


            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: |
                    
                    ${{ vars.DOCKER_USER_NAME }}/$repo_name
                
                tags: |
                    type=ref,event=branch
                    type=ref,event=pr
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}
                    type=sha

            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                    username: ${{ vars.DOCKER_USER_NAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}


            - name: Build a Docker images
              if: ${{ github.ref_type == 'tag' }}
              run: |
                   
                    docker build -t ${{ vars.DOCKER_USER_NAME }}/$repo_name:$version_no .
                    docker images
                  
       
      
            - name: push Docker image
              if: ${{ github.ref_type == 'tag' }}
              uses: docker/build-push-action@v5
              with:
                    context: .
                    push: true
                    tags: |
                        ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}