name: Playwright Tests executing in docker container
on:
  push:
    branches: [ testrun/** ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
    container-test-job:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        name: execute a test from a image
        steps:        
            - name: set up a docker environement
              uses: docker/setup-buildx-action@v3   

            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USER_NAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: pull and run the test from image
              run: |
                docker pull thanandock/playwright-ui-typescript:latest
                docker run  -v ./playwright-report:/app/playwright-report \
                      thanandock/playwright-ui-typescript:latest \
                      -c "npx playwright test"

            - name: Add the test summary status back to PR comment
              uses: mshick/add-pr-comment@v2
              if: (contains(fromJSON('["pull_request", "push"]'), github.event_name))
              env:
                content: $(cat  ./playwright-report/result.txt)
              with:
                message: |
                        **Howdie!** Summary status ${{ env.content }}
                message-failure: |
                        Workflow failed
    
    publish-reports:
        if: ${{ contains(github.ref,'main')}}
        needs: [ container-test-job ]
        runs-on: ubuntu-latest
        permissions: 
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
        - name: Setup Pages
          uses: actions/configure-pages@v3

        - name: Upload Artifact for pages
          uses: actions/upload-pages-artifact@v1
          with:
        # location of the coverage artifacts
                path: "./playwright-report"

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
            
       
        

